### ISSUE TITLE
BIN to EZI

### ISSUE THREAD

**Issue by keithecutest** [Arrowgene/Arrowgene.StepFile#2]
Is there any way to get EZI data from the BIN files in the pattern directory?

**Comment by sebastian-heinz** [comment]
Could you let me know which file you are looking at? (if possible specify the path) just to understand where you are at.

**Comment by keithecutest** [comment]
If unpacking EzData.tro, we can find the "Sound" folder, and we also figure out that pattern files are stored there, song by song.

As you know, PTN file is the real pattern data, works as same as EZ file in the arcade, and BIN file stored together defines the sound data information of each pattern file, working as same as the EZI file in the arcade.

Those BIN files are written in binary way, but EZI files contain the human-readable text data. So I want to figure out the actual EZI data from the BIN files I mentioned. Is there any solution?

**Comment by sebastian-heinz** [comment]
I haven't had the chance to study the .bin format yet.

The latest addition was that you can convert the .pt file.
If you open the tab with the music note "New Ez2On StepFile" there should be another button called "Pt2Ez" wich allows you to select a .pt-file.

It will then create two new files from that:
.pt -> .ez and .ezi

So I do not think that .bin is the .ezi file of arcade thought, I might be wrong. But if you tell me more about the bin or what we should do with it, then I might be able to add the desired functionality if the above is not what you need.

**Comment by keithecutest** [comment]
I have downloaded the project here and tried to build it using Visual Studio 2019, but the error occurs because one file is missing. So I cannot try the functions of this program now.

Missing file : \Arrowgene.StepFile.Gui\Control\Ez2On\Build\Ez2OnBuildTabController.cs

**Comment by sebastian-heinz** [comment]
Oh, thank you for the report. I made a /Build folder for a function that allows me to build a new EzData.Tro file automatically from decrypted folder. But the .gitignore file excludes an /Build folder as it is the same name for temporary build output by visual studio which I did not want to have in git.

Im currently not near my machine to provide the missing file.

I suggest you remove that file and all references from solution and you should be able to run it.

If not please wait around 7 hours till i am off work and can fix this issue.

**Comment by keithecutest** [comment]
I've been waiting for the missing file, and it seems to be still missing here...?

**Comment by sebastian-heinz** [comment]
Should be fixed now

**Comment by keithecutest** [comment]
Okay, all files are ready, but some errors occur while building.

CS0006 : Metadata file '..\packages\Microsoft.CodeAnalysis.Analyzers.2.6.1\analyzers\dotnet\cs\Microsoft.CodeAnalysis.Analyzers.dll' could not be found

CS0006 : Metadata file '..\packages\Microsoft.CodeAnalysis.Analyzers.2.6.1\analyzers\dotnet\cs\Microsoft.CodeAnalysis.CSharp.Analyzers.dll' could not be found

What program or add-ons should I install in order to fix those errors, build and test this application?

**Comment by sebastian-heinz** [comment]
Hm not sure why these references were in .csproj. I removed them. 
Thank you for testing, could you try the updated code?
